# Generated by Django 3.2 on 2022-12-10 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('helper_type', models.CharField(blank=True, choices=[('FDBNK', 'Food Assistance'), ('REUAS', 'Rent / Utilities Assistance'), ('ELEMP', 'Entry-Level Job Employer'), ('JOSKT', 'Job Skills Educator'), ('MHSER', 'Mental Health Services Organization or Individual'), ('DAREH', 'Drug / Alcohol Rehab Services Organization'), ('SCHOL', 'Scholarship Offerer'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('body', martor.models.MartorField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='helper_thumbnails')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='helper_cover_photos')),
                ('hours_of_operation', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='wiki_moderated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
