# Generated by Django 3.2 on 2022-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
