# Generated by Django 3.2 on 2022-12-11 22:04

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikientry_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='cover_photo',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='thumbnail',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
