# Generated by Django 3.2 on 2022-12-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_wikientry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikientry',
            old_name='body',
            new_name='description',
        ),
    ]
