# Generated by Django 3.2 on 2022-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_wikientry_helper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='hours_of_operation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
