# Generated by Django 3.2 on 2022-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_alter_wikientry_hours_of_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
