# Generated by Django 3.2 on 2022-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_wikientry_helper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
