# Generated by Django 3.2 on 2022-12-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_wikientry_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
