# Generated by Django 3.2 on 2022-12-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_wikientry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='wiki_entry_cover_photos'),
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='wiki_entry_thumbnails'),
        ),
    ]
