# Generated by Django 3.2 on 2022-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_auto_20221213_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='helper_type',
            field=models.CharField(blank=True, choices=[('food', 'Food Assistance'), ('rent_utilities', 'Housing / Rent Assistance'), ('entry_level_job', 'Entry-Level Job Employer'), ('develop_skills', 'Job Skills Educator'), ('mental_health_rehab', 'Mental Health or Rehab Services'), ('scholarships', 'Scholarship Offerer'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
