# Generated by Django 3.2 on 2022-12-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_alter_wikientry_helper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikientry',
            name='title',
            field=models.CharField(default='Untitled', max_length=255, unique=True),
        ),
    ]
