# Generated by Django 3.2 on 2022-12-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_alter_wikientry_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wikientry',
            unique_together={('title', 'address', 'description')},
        ),
    ]
