# Generated by Django 3.2 on 2023-01-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_alter_wikientry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wikientry',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
