"""
Django settings for stdepaul project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('STDEPAUL_SETTINGS_SECRET_KEY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django.contrib.postgres',

    'api',
    'root_app',
    'wiki',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    #'allauth.socialaccount.providers.facebook',
    #'allauth.socialaccount.providers.google',

    'vote',
    'django_messages',
    'captcha',

    'rest_framework',
    'rest_framework.authtoken',

    'martor',
    'storages',
]

RECAPTCHA_REQUIRED_SCORE = 0.85
# recaptcha v3 

"""
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': '',
        }
    },
    'google': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        }
    }
}
"""

# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get('IS_PRODUCTION') != 'True':
    IS_PRODUCTION = False
else:
    IS_PRODUCTION = True

if not IS_PRODUCTION:
    DEBUG = True
    # set to static locally for collectstatic
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    ALLOWED_HOSTS = ['*']
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),
    )
    SECURE_SSL_REDIRECT = False
else:
    DEBUG = False
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    ALLOWED_HOSTS = os.environ.get('STDEPAUL_ALLOWED_HOSTS').split(',')
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),   
    )

    # autoredirect to https
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
AWS_ACCESS_KEY_ID = os.environ.get('STDEPAUL_AWS_KEY')
AWS_SECRET_ACCESS_KEY = os.environ.get('STDEPAUL_AWS_SECRET')
AWS_STORAGE_BUCKET_NAME = os.environ.get('STDEPAUL_S3_BUCKET_NAME')
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

APPEND_SLASH = True 

MARTOR_ENABLE_CONFIGS = {
    'imgur': 'false',
}

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

EMAIL_BACKEND = "sgbackend.SendGridBackend"
SENDGRID_API_KEY = os.environ.get('STDEPAUL_SENDGRID_API_KEY')
DEFAULT_FROM_EMAIL = 'michael@stdepaul.org'

SITE_ID = 1

RECAPTCHA_PUBLIC_KEY = os.environ.get('STDEPAUL_RECAPTCHA_KEY')
RECAPTCHA_PRIVATE_KEY = os.environ.get('STDEPAUL_RECAPTCHA_SECRET')

LOGIN_REDIRECT_URL = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'stdepaul.urls'


WSGI_APPLICATION = 'stdepaul.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

import dj_database_url
dbpw = os.environ.get('STDEPAUL_DBPW')
db_name = os.environ.get('STDEPAUL_DB_NAME')
DATABASES = {
    'default': dj_database_url.config(default='postgres://postgres:%s@localhost:5432/%s' % (dbpw, db_name))
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
