# Generated by Django 3.0 on 2022-12-10 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='user_thumbnails')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='user_cover_photos')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='helper_thumbnails')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='helper_cover_photos')),
                ('hours_of_operation', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper_type', models.CharField(blank=True, choices=[('FDBNK', 'Food Assistance'), ('REUAS', 'Rent / Utilities Assistance'), ('ELEMP', 'Entry-Level Job Employer'), ('JOSKT', 'Job Skills Educator'), ('MHSER', 'Mental Health Services Organization or Individual'), ('DAREH', 'Drug / Alcohol Rehab Services Organization'), ('SCHOL', 'Scholarship Offerer')], max_length=255, null=True)),
                ('verification_document_1', models.ImageField(blank=True, null=True, upload_to='helper_verification_document_1_folder')),
                ('verification_document_2', models.ImageField(blank=True, null=True, upload_to='helper_verification_document_2_folder')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(related_name='moderated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
