# Generated by Django 3.2 on 2022-12-10 20:52

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0002_comment_post_postreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_type',
            field=models.CharField(blank=True, choices=[('FDBNK', 'Food Assistance'), ('REUAS', 'Rent / Utilities Assistance'), ('ELEMP', 'Entry-Level Job Employer'), ('JOSKT', 'Job Skills Educator'), ('MHSER', 'Mental Health Services Organization or Individual'), ('DAREH', 'Drug / Alcohol Rehab Services Organization'), ('SCHOL', 'Scholarship Offerer'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
