# Generated by Django 3.2 on 2022-12-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0003_auto_20221210_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='help_type',
            field=models.CharField(blank=True, choices=[('IWTH', 'I want to help'), ('INH', 'I need help')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
