# Generated by Django 3.2 on 2022-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0005_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
