# Generated by Django 3.2 on 2022-12-11 22:04

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0007_commentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='cover_photo',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='thumbnail',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='verification_document_1',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='verification_document_2',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
