# Generated by Django 3.2 on 2022-12-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0008_auto_20221211_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='helper_cover_photos'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='helper_thumbnails'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='verification_document_1',
            field=models.ImageField(blank=True, null=True, upload_to='helper_verification_document_1_folder'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='verification_document_2',
            field=models.ImageField(blank=True, null=True, upload_to='helper_verification_document_2_folder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_cover_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_thumbnails'),
        ),
    ]
