# Generated by Django 3.2 on 2022-12-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0010_alter_helper_hours_of_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='name',
        ),
        migrations.AddField(
            model_name='helper',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
