# Generated by Django 3.2 on 2022-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0011_auto_20221212_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='help_type',
            field=models.CharField(blank=True, choices=[('HLPR', 'Helper'), ('HLPE', 'Helpee')], max_length=255, null=True),
        ),
    ]
