# Generated by Django 3.2 on 2022-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0012_alter_post_help_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('HLPR', 'Helper'), ('HLPE', 'Helpee')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='help_type',
            field=models.CharField(blank=True, choices=[('FDBNK', 'Food Assistance'), ('REUAS', 'Rent / Utilities Assistance'), ('ELEMP', 'Entry-Level Job Employer'), ('JOSKT', 'Job Skills Educator'), ('MHSER', 'Mental Health Services Organization or Individual'), ('DAREH', 'Drug / Alcohol Rehab Services Organization'), ('SCHOL', 'Scholarship Offerer'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
