# Generated by Django 3.2 on 2022-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0014_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='helper_type',
            field=models.CharField(blank=True, choices=[('food', 'Food Assistance'), ('rent_utilities', 'Rent / Utilities Assistance'), ('entry_level_job', 'Entry-Level Job Employer'), ('develop_skills', 'Job Skills Educator'), ('mental_health', 'Mental Health Services Organization or Individual'), ('rehab', 'Drug / Alcohol Rehab Services Organization'), ('scholarships', 'Scholarship Offerer'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='help_type',
            field=models.CharField(blank=True, choices=[('food', 'Food Assistance'), ('rent_utilities', 'Rent / Utilities Assistance'), ('entry_level_job', 'Entry-Level Job Employer'), ('develop_skills', 'Job Skills Educator'), ('mental_health', 'Mental Health Services Organization or Individual'), ('rehab', 'Drug / Alcohol Rehab Services Organization'), ('scholarships', 'Scholarship Offerer'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
