# Generated by Django 3.2 on 2022-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0015_auto_20221212_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('helpees', 'helpers'), ('helpers_indv', 'helpees')], max_length=255, null=True),
        ),
    ]
