# Generated by Django 3.2 on 2022-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0016_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('helpers_indv', 'helpers'), ('helpees', 'helpees')], max_length=255, null=True),
        ),
    ]
