# Generated by Django 3.2 on 2022-12-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0017_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='hours_of_operation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
