# Generated by Django 3.2 on 2022-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_app', '0020_auto_20221213_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
